<?php
/*Desarrolle un para estimar el valor de "pi" usando la siguiente suma infinita desarrollada por leibniz*/

/*$numero, VARIABLE DE TIPO ENTERO EN LA QUE SE ALMACENARA EL DATO QUE EL USUARIO INGRESE POR TECLADO*/
$numero=readline("INGRESE UN NUMERO: ");

/*$sumatoria, VARIABLE DE TIPO ENTERO EN LA QUE SE ALMACENENARA UNA SUMA DEL PROCESO QUE SE HARA EN UN "for" PARA DETERMINAR UN SUMATORIA INFINITA DE CUALQUIER NUMERO INGRESADO*/
$sumatoria=0;

/*EN EL CICLO "for", DECLARAMOS UNA VARIABLE $contador DE TIPO ENTERO QUE NOS PERMITIRA CONTAR LAS VECES QUE ESTE SE REPETIRA CON EL FIN DE DAR IGUALDAD AL NUMERO QUE SE INGRESA POR MEDIO DEL TECLADO HACIENDO UNA COMPARACION Y AUMENTANDO EL CONTADOR DE UNO EN UNO HASTA QUE SE IGUAL MENOR O IGUAL QUE EL NUMERO INGRESADO*/
for ($contador=0; $contador<=$numero; $contador++){
	/*EN ESTA CONDICION VEREMOS LA APLICACION DE LA FORMULA DE LEIBNIZ EN FORMA LINEAL Y NO ALGEBRAICA*/
	$sumatoria = $sumatoria + pow(-1, $contador) / (2*$contador+1);
	
}
/*UNA VEZ TERMINAMOS EL PROCESO ANTERIO Y QUE EL CICLO "for" NO SAQUE DEL BLUCE TENDREMOS QUE HACER UNA ULTIMA SENTENCIA QUE CONSISTIRA EN MULTIPLICA 4 POR LA SUMATORIA ACUMULADA ANTERIORMENTE*/
$resultado= (4*$sumatoria);
/*ECHO ME PERMITIRA MOSTRAR EL RESULTADO DE DICHA OPERACION*/
echo "EL RESULTADO DE LA OPERACION ES : $resultado \n";
?>
